TOPDIR = ..
LIB = libctree.a
CSRCS = vec.c map.c parser.c lexer.c tree.c

CFLAGS = -I${TOPDIR}/include/ctree -g -O2
LDFLAGS =

include ${TOPDIR}/make/comm.mk
include ${TOPDIR}/make/c.mk
include ${TOPDIR}/user.mk
