TOPDIR = ..
LIB = libcast.a
CSRCS = vec.c map.c parser.c lexer.c tree.c allocator.c printer.c

CFLAGS = -I${TOPDIR}/include/cast -g -O2
LDFLAGS =

include ${TOPDIR}/make/comm.mk
include ${TOPDIR}/make/c.mk
include ${TOPDIR}/user.mk
